
(() => {
 const cfg=window.UNION_PORTAL_CONFIG||{discordWebhook:'',discordEnabled:false};
 const read=(k)=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
 const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const uid=(prefix)=>`${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
 async function discord(content,embed){if(!cfg.discordEnabled||!cfg.discordWebhook)return;try{await fetch(cfg.discordWebhook,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,embeds:embed?[embed]:[]})})}catch(e){console.warn('Discord webhook failed',e)}}
 document.querySelectorAll('[data-application-form]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));const record={id:uid('APP'),type:form.dataset.applicationType,createdAt:new Date().toISOString(),status:'Pending Review',response:'',data};const all=read('unionApplications');all.unshift(record);write('unionApplications',all);await discord(record.type==='Whitelist Application'?'A new whitelist application has been submitted.':`A new ${record.type} has been submitted.`,{title:`New application: ${record.type}`,description:`Reference: ${record.id}`,color:10181046});const msg=form.querySelector('.portal-form-message');if(msg)msg.textContent=`Application submitted. Reference: ${record.id}`;form.reset();}));
 const ticketForm=document.getElementById('support-ticket-form');
 if(ticketForm)ticketForm.addEventListener('submit',async e=>{e.preventDefault();const record={id:uid('TKT'),createdAt:new Date().toISOString(),status:'Open',response:'',category:document.getElementById('ticket-category').value,name:document.getElementById('ticket-name').value,priority:document.getElementById('ticket-priority').value,subject:document.getElementById('ticket-subject').value,details:document.getElementById('ticket-details').value};const all=read('unionTickets');all.unshift(record);write('unionTickets',all);await discord(`Management Ticket ${record.id} has been opened.`,{title:record.subject,description:record.details.slice(0,1000),color:10181046});document.getElementById('ticket-form-message').textContent=`Ticket opened. Reference: ${record.id}`;ticketForm.reset();renderMyTickets();});
 function renderMyTickets(){const el=document.getElementById('local-ticket-list');if(!el)return;const all=read('unionTickets');el.innerHTML=all.length?all.map(t=>`<article class="local-ticket-card"><div class="local-ticket-ref">${t.id}</div><div><h3>${t.subject}</h3><p>${new Date(t.createdAt).toLocaleString()} · ${t.category}</p>${t.response?`<div class="ticket-response"><strong>Staff response</strong><p>${t.response}</p></div>`:''}</div><span class="local-ticket-status">${t.status}</span></article>`).join(''):'<div class="ticket-empty-state"><strong>No tickets yet</strong><p>Your submitted tickets will appear here.</p></div>'}
 renderMyTickets();
 const panel=document.getElementById('staff-panel-content');
 if(panel){let tab='tickets';document.querySelectorAll('[data-staff-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-staff-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');tab=b.dataset.staffTab;renderStaff();}));
 function stats(){const t=read('unionTickets'),a=read('unionApplications');document.getElementById('staff-stats').innerHTML=`<article><span>OPEN TICKETS</span><strong>${t.filter(x=>x.status!=='Closed').length}</strong></article><article><span>PENDING APPLICATIONS</span><strong>${a.filter(x=>x.status==='Pending Review').length}</strong></article><article><span>TOTAL RECORDS</span><strong>${t.length+a.length}</strong></article>`}
 async function save(kind,id){const key=kind==='ticket'?'unionTickets':'unionApplications',arr=read(key),item=arr.find(x=>x.id===id);if(!item)return;item.status=document.querySelector(`[data-status="${id}"]`).value;item.response=document.querySelector(`[data-response="${id}"]`).value.trim();write(key,arr);await discord(kind==='ticket'?`Management Ticket ${id} has been responded to.`:`Application ${id} has been updated.`,{title:`${kind==='ticket'?'Ticket':'Application'} update`,description:item.response||item.status,color:10181046});renderStaff();}
 function renderStaff(){stats();if(tab==='settings'){panel.innerHTML=`<div class="settings-panel"><span>DISCORD INTEGRATION</span><h2>Prepared for final setup</h2><p>Open <code>js/portal-config.js</code> when you are ready. Add the webhook URL and change <code>discordEnabled</code> to <code>true</code>. No Discord role restrictions or authentication are active yet.</p><pre>window.UNION_PORTAL_CONFIG = {\n  discordWebhook: '',\n  discordEnabled: false\n};</pre></div>`;return}const isTicket=tab==='tickets',arr=read(isTicket?'unionTickets':'unionApplications');panel.innerHTML=`<div class="staff-record-list">${arr.length?arr.map(x=>`<article class="staff-record"><header><div><span>${x.id}</span><h3>${isTicket?x.subject:x.type}</h3><p>${new Date(x.createdAt).toLocaleString()}</p></div><select data-status="${x.id}">${(isTicket?['Open','In Progress','Awaiting Player','Closed']:['Pending Review','Interview','Accepted','Declined']).map(s=>`<option ${x.status===s?'selected':''}>${s}</option>`).join('')}</select></header><div class="staff-record-data">${isTicket?`<p><strong>${x.category}</strong> · ${x.priority}</p><p>${x.details}</p>`:Object.entries(x.data||{}).map(([k,v])=>`<p><strong>${k.replace(/([A-Z])/g,' $1')}</strong><span>${String(v)}</span></p>`).join('')}</div><label>Staff response<textarea data-response="${x.id}" rows="4">${x.response||''}</textarea></label><button class="primary-button" data-save-kind="${isTicket?'ticket':'application'}" data-save-id="${x.id}">Save Update</button></article>`).join(''):'<div class="ticket-empty-state"><strong>No records yet</strong><p>New submissions will appear here.</p></div>'}</div>`;panel.querySelectorAll('[data-save-id]').forEach(b=>b.addEventListener('click',()=>save(b.dataset.saveKind,b.dataset.saveId)));}
 renderStaff();}
})();
