(() => {
  'use strict';
  const API_BASE=(window.PORTAL_CONFIG&&PORTAL_CONFIG.API_BASE_URL)||(window.UNION_CONFIG&&UNION_CONFIG.API_BASE_URL)||'https://union-roleplay-api.danielclifford2808.workers.dev';
  const token=()=>window.Auth?.getAccessToken?.()||localStorage.getItem('union_access_token')||'';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>v?new Date(Number(v)).toLocaleString('en-GB'):'—';
  async function api(path,opt={}){const r=await fetch(API_BASE+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(opt.headers||{})},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d;}
  function panel(){return document.getElementById('staff-panel-content')}
  async function render(){const p=panel();if(!p)return;p.innerHTML='<div class="admin-empty">Loading administration hub…</div>';try{const d=await api('/api/staff/admin/overview');p.innerHTML=`<div class="admin-hub"><section class="admin-hero"><div><span>UNION CONTROL CENTRE</span><h2>Server Administration</h2><p>Website support, recruitment, player records and staff accountability. No MDT integration.</p></div><button class="admin-refresh" id="admin-refresh">Refresh data</button></section><section class="admin-metrics">${metric(d.metrics.open_tickets,'Open tickets')}${metric(d.metrics.pending_applications,'Pending applications')}${metric(d.metrics.users,'Registered users')}${metric(d.metrics.actions_7d,'Staff actions · 7 days')}</section><section class="admin-grid"><div class="admin-card"><header><span>STAFF PERFORMANCE</span><h3>Activity leaderboard</h3></header>${staffTable(d.staff||[])}</div><div class="admin-card"><header><span>RECENT ACTIVITY</span><h3>Audit feed</h3></header><div class="admin-feed">${feed(d.activity||[])}</div></div></section><section class="admin-card"><header><span>PLAYER RECORDS</span><h3>Search users and add internal staff notes</h3></header><div class="admin-player-tools"><div class="admin-search-row"><input id="admin-player-query" placeholder="Union ID, Discord ID or username"><button id="admin-player-search">Search</button></div><div id="admin-player-results" class="admin-results"></div></div><div id="admin-note-panel" class="admin-note-panel" hidden></div></section></div>`;document.getElementById('admin-refresh').onclick=render;document.getElementById('admin-player-search').onclick=searchPlayers;document.getElementById('admin-player-query').addEventListener('keydown',e=>{if(e.key==='Enter')searchPlayers()});}catch(e){p.innerHTML=`<div class="admin-error"><strong>Administration unavailable</strong><p>${esc(e.message)}</p></div>`}}
  const metric=(n,l)=>`<article class="admin-metric"><strong>${Number(n||0).toLocaleString('en-GB')}</strong><span>${esc(l)}</span></article>`;
  function staffTable(rows){if(!rows.length)return'<div class="admin-empty">No staff activity recorded yet.</div>';return`<table class="admin-table"><thead><tr><th>Staff member</th><th>Applications</th><th>Ticket actions</th><th>Total</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.actor_name||r.actor_discord_id||'Unknown')}</strong></td><td>${r.application_actions||0}</td><td>${r.ticket_actions||0}</td><td>${r.total_actions||0}</td></tr>`).join('')}</tbody></table>`}
  function feed(rows){return rows.length?rows.map(r=>`<article><strong>${esc(r.action||'Updated')}</strong><p>${esc(r.reference||'')} ${r.details?'· '+esc(r.details):''}</p><time>${esc(r.actor||'Union Staff')} · ${fmt(r.created_at)}</time></article>`).join(''):'<div class="admin-empty">No recent audit activity.</div>'}
  async function searchPlayers(){const q=document.getElementById('admin-player-query').value.trim(), box=document.getElementById('admin-player-results');if(!q){box.innerHTML='<div class="admin-empty">Enter a search value.</div>';return}box.innerHTML='<div class="admin-empty">Searching…</div>';try{const d=await api('/api/staff/admin/users?q='+encodeURIComponent(q));box.innerHTML=d.users.length?d.users.map(u=>`<button class="admin-user" data-user-id="${u.id}"><strong>${esc(u.display_name||u.username||'Unknown user')}</strong><span>Union ID: ${esc(u.union_id||'Not assigned')} · Discord: ${esc(u.discord_id||'Unknown')} · ${u.ticket_count||0} tickets · ${u.application_count||0} applications</span></button>`).join(''):'<div class="admin-empty">No matching users found.</div>';box.querySelectorAll('[data-user-id]').forEach(b=>b.onclick=()=>openUser(b.dataset.userId));}catch(e){box.innerHTML=`<div class="admin-error">${esc(e.message)}</div>`}}
  async function openUser(id){const box=document.getElementById('admin-note-panel');box.hidden=false;box.innerHTML='<div class="admin-empty">Loading record…</div>';try{const d=await api('/api/staff/admin/users/'+encodeURIComponent(id));const u=d.user;box.innerHTML=`<h3>${esc(u.display_name||u.username||'Player record')}</h3><p>Union ID: ${esc(u.union_id||'Not assigned')} · Discord ID: ${esc(u.discord_id||'Unknown')}</p><div id="admin-notes">${notes(d.notes||[])}</div><div class="admin-note-form"><textarea id="admin-note-text" maxlength="2000" placeholder="Internal staff note — players cannot see this"></textarea><button id="admin-note-save">Add note</button></div>`;document.getElementById('admin-note-save').onclick=async()=>{const text=document.getElementById('admin-note-text').value.trim();if(!text)return;await api('/api/staff/admin/users/'+encodeURIComponent(id)+'/notes',{method:'POST',body:JSON.stringify({text})});openUser(id)};}catch(e){box.innerHTML=`<div class="admin-error">${esc(e.message)}</div>`}}
  function notes(rows){return rows.length?rows.map(n=>`<article class="admin-note"><strong>${esc(n.actor_name||'Union Staff')}</strong><p>${esc(n.note)}</p><small>${fmt(n.created_at)}</small></article>`).join(''):'<div class="admin-empty">No internal notes for this player.</div>'}
  document.addEventListener('DOMContentLoaded',()=>{document.querySelector('[data-staff-tab="administration"]')?.addEventListener('click',()=>setTimeout(render,0));});
})();
