
// Cloudflare Worker for Union Roleplay applications, support and Discord role-protected staff panel.
// Bind a D1 database as DB. Add secrets: DISCORD_CLIENT_SECRET, DISCORD_BOT_TOKEN,
// TOKEN_SECRET, APPLICATION_WEBHOOK, SUPPORT_WEBHOOK.
const cors=(env)=>({'Access-Control-Allow-Origin':env.SITE_URL,'Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET, POST, OPTIONS'});
const json=(data,status=200,env={SITE_URL:'*'})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...cors(env)}});
const b64=o=>btoa(unescape(encodeURIComponent(JSON.stringify(o)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const unb64=s=>JSON.parse(decodeURIComponent(escape(atob(s.replaceAll('-','+').replaceAll('_','/')))));
async function hmac(data,secret){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const s=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(data));return [...new Uint8Array(s)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function makeToken(payload,secret){const p=b64(payload);return p+'.'+await hmac(p,secret)}
async function verifyToken(t,secret){if(!t)return null;const [p,s]=t.split('.');if(!p||s!==await hmac(p,secret))return null;const d=unb64(p);if(d.exp<Date.now())return null;return d}
async function memberHasRole(userId,env){const r=await fetch(`https://discord.com/api/v10/guilds/${env.DISCORD_GUILD_ID}/members/${userId}`,{headers:{Authorization:`Bot ${env.DISCORD_BOT_TOKEN}`}});if(!r.ok)return false;const m=await r.json();const allowed=env.STAFF_ROLE_IDS.split(',').map(x=>x.trim());return m.roles.some(x=>allowed.includes(x))}
function safeFields(data){const out={};for(const [k,v] of Object.entries(data)){if(k==='type')continue;out[k]=String(v).slice(0,4000)}return out}
async function notify(url,title,data){if(!url)return;const fields=Object.entries(data).slice(0,20).map(([name,value])=>({name:name.replace(/([A-Z])/g,' $1'),value:String(value||'Not supplied').slice(0,1000),inline:false}));await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({embeds:[{title,description:'A new website submission is ready in the Union staff panel.',color:10311167,fields,timestamp:new Date().toISOString(),footer:{text:'Union Roleplay Website'}}]})})}
export default {async fetch(req,env){const u=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{headers:cors(env)});
 if(u.pathname==='/auth/login'){const state=crypto.randomUUID();const q=new URLSearchParams({client_id:env.DISCORD_CLIENT_ID,response_type:'code',redirect_uri:env.DISCORD_REDIRECT_URI,scope:'identify',state});return Response.redirect('https://discord.com/oauth2/authorize?'+q,302)}
 if(u.pathname==='/auth/callback'){const code=u.searchParams.get('code');const body=new URLSearchParams({client_id:env.DISCORD_CLIENT_ID,client_secret:env.DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code,redirect_uri:env.DISCORD_REDIRECT_URI});const tr=await fetch('https://discord.com/api/v10/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!tr.ok)return new Response('Discord login failed',{status:401});const tok=await tr.json();const ur=await fetch('https://discord.com/api/v10/users/@me',{headers:{Authorization:`Bearer ${tok.access_token}`}});const user=await ur.json();if(!await memberHasRole(user.id,env))return Response.redirect(env.SITE_URL+'/staff.html#error=role',302);const jwt=await makeToken({id:user.id,name:user.username,exp:Date.now()+8*60*60*1000},env.TOKEN_SECRET);return Response.redirect(env.SITE_URL+'/staff.html#token='+encodeURIComponent(jwt),302)}
 if(u.pathname==='/api/submit'&&req.method==='POST'){const raw=await req.json();const data=safeFields(raw);const category=raw.type==='support'?'support':'application';const subtype=category==='support'?data.supportType:data.applicationType;const title=category==='support'?data.subject:(subtype||'New application').replaceAll('_',' ');const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO submissions (id,category,subtype,title,submitter,payload,status,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,category,subtype,title,data.discord||data.name||'Unknown',JSON.stringify(data),'new',new Date().toISOString()).run();const webhook=category==='support'?env.SUPPORT_WEBHOOK:env.APPLICATION_WEBHOOK;await notify(webhook,category==='support'?`New ${subtype.replaceAll('_',' ')} ticket`:`New ${subtype.replaceAll('_',' ')} application`,data);return json({ok:true,id},201,env)}
 if(u.pathname==='/api/submissions'){const bearer=req.headers.get('Authorization')?.replace('Bearer ','');const auth=await verifyToken(bearer,env.TOKEN_SECRET);if(!auth||!await memberHasRole(auth.id,env))return json({error:'You do not have an authorised staff role.'},403,env);const {results}=await env.DB.prepare('SELECT * FROM submissions ORDER BY created_at DESC LIMIT 250').all();return json({items:results},200,env)}
 return json({name:'Union Roleplay API',ok:true},200,env)}}
